### ISSUE TITLE
`No such process` error

### ISSUE THREAD

**Issue by allspiritseve** [mweitzel/firetower#1]
Getting an error with the vim plugin every time I save:

```
/usr/local/bin/firetower: line 124: kill: (16106) - No such process
/usr/local/bin/firetower: line 125: kill: (16106) - No such process
```

The `pid` changes every time.

Using `firetower -r` from the command line works fine.

**Comment by mweitzel** [comment]
This was intermittent for me, something under 1% of saves.

Simpler repro: `$ firetower -r & firetower -r`

**Comment by mweitzel** [comment]
Thanks @allspiritseve
